# Generated by Django 5.2.4 on 2025-07-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_registration_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
