# Generated by Django 5.2.4 on 2025-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.IntegerField()),
                ('jobname', models.CharField()),
                ('description', models.CharField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
