# Generated by Django 5.2.4 on 2025-07-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.IntegerField()),
                ('jobname', models.CharField()),
                ('description', models.CharField()),
                ('salary', models.FloatField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='JobList',
        ),
    ]
